### ISSUE TITLE
Customer Dashboard Feature 

### ISSUE THREAD

**Issue by mccallofthewild** [Sifchain/sifchain-ui#356]
@mccallofthewild commented on [Wed Oct 27 2021](https://github.com/Sifchain/ui/issues/63)

Make a guest state and keep in mind users who have nothing
Think about the entire new user log-in flow
- @caseyturnerarrington 

Figma: https://www.figma.com/file/gcSOKvZrSNKmvFDFMqrbTt/Sifchain?node-id=3199%3A22566

- USD Value of:
    - Balance
    - Pooled
    - Staked
    - Rewards
- Newsfeed
    - Medium RSS Feed  [https://medium.com/feed/@sifchain](https://medium.com/feed/@sifchain)
- Quick Swap
    - Opens confirm w/ all swap details
- Changelog
    - Pull changelog list (truncated)
- Stats Sidebar?
- Social links
- Quick transfer
    - Confirm modal + send
- Top reward pools

- Additional Ideas:
    - 1) Your Total Locked Balance
        - Include: Total Staked Value, Total in Liquidity Pools
    - 2) Quick Send:
        - To be able to transfer any token to another sifchain address
        
    - New Idea:

**Comment by bksifchain** [comment]
@ajoslin  - Pls break down the remaining work by component. And then I will break up tickets for it.

**Comment by ajoslin** [comment]
## Dashboard Components

Branch: feature/dashboard

Remaining items


#### Newsfeed component

Pull RSS feed from Sifchain medium and display in card

#### Quick Swap component

* Redesign swap to hide extra information behind a gear icon (like Uniswap does)
* Have the gear icon, when clicked, just change the content of the swap screen (or use a popup, but our tooltip lib is not good for dynamic content with Vue...)
* Embed this smaller swap in a card on dashboard page

### Quick Transfer

This is literally just to do a send tx of any Sifchain asset from one Sif wallet to another. This feature is needed because Keplr doesn't list all our new tokens as soon as we add them, we have to manually submit a request to Keplr and wait for a release.

While waiting for the release, users aren't able to select tokens to send them in Keplr so we'd like to create a GUI for them.

* Should be pretty simple to build... can start it from scratch or pick it up from `feature/transfer-a-la-carte`

### Top Reward Pools

* If user is connected and has one or more deposits...
Display all the user's deposited pools here. Just add 1 more column for "Your Pool Value".

* Otherwise, if user is not connected or has 0 deposits...
Just display the top 5 reward pools by Reward APR.
